version: '3.7'
services:
  chromedriver:
    image: blueimp/chromedriver
    init: true
    environment:
      - EXPOSE_X11=true
  test:
    build: .
    init: true
    command: index.test.js
    read_only: true
    tmpfs: /tmp
    environment:
      - X11_HOST=chromedriver
      - WAIT_FOR_HOSTS=chromedriver:6000
    volumes:
      - .:/opt:ro
    depends_on:
      - chromedriver
