version: '3.7'
services:
  chromedriver:
    image: blueimp/chromedriver
    init: true
    environment:
      - EXPOSE_X11=true
  test:
    build: .
    init: true
    command: index.test.js
    environment:
      - WAIT_FOR_HOSTS=chromedriver:6000
    volumes:
      - .:/opt
    depends_on:
      - chromedriver
